name: Deploy-Jar

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - name: Deploy a jar file
        run: gh release create $GITHUB_REF_NAME *.jar
        env:
          # before using this, please set 'read and write permissions'
          # on the Action settings page of repo.
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
        working-directory: build/libs